export const REQUEST_ALL_PRODUCTS = "REQUEST_ALL_PRODUCTS";
export const RECEIVE_ALL_PRODUCTS = "RECEIVE_ALL_PRODUCTS";
export const LOAD_FIRST = "LOAD_FIRST";
export const SWIPE_RIGHT = "SWIPE_RIGHT";
export const SWIPE_LEFT = "SWIPE_LEFT";